import { Router } from 'express';
import { changePassword, login, adminLogin, logout, me, register } from '../controllers/auth.js';
import { createDocumentType, downloadDocument, listDocumentTypes as listAdminDocumentTypes, listDocuments, listUsers, reviewDocument, reviewUser, setCredentials, updateDocumentType } from '../controllers/adminUsers.js';
import { downloadOwnDocument, getProfile, listDocumentTypes, updateProfile, uploadDocuments, uploadProfilePhoto } from '../controllers/profile.js';
import { dashboard } from '../controllers/dashboard.js';
import { createCollateral, listCollaterals, updateCollateralStatus } from '../controllers/collaterals.js';
import { createLoan, getLoan, listLoans, listProducts, updateLoanStatus } from '../controllers/loans.js';
import { createPayment, getLoanRepaymentSummary, listRepayments, paymentReceipt, paymentReport, reconcilePayment } from '../controllers/repayments.js';
import { listNotifications, markNotificationRead } from '../controllers/notifications.js';
import { adminDashboard, listAuditLogs, report } from '../controllers/adminDashboard.js';
import { requireAdmin, requireAuth, requireSuperAdmin } from '../middleware/auth.js';
import { wrap } from '../utils/async.js';
import multer from 'multer';

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { files: 5, fileSize: 5 * 1024 * 1024 }, fileFilter: (req, file, callback) => callback(null, ['application/pdf', 'image/jpeg', 'image/png'].includes(file.mimetype)) });
router.post('/auth/register', upload.array('documents', 5), wrap(register));
router.post('/auth/login', wrap(login));
router.post('/auth/admin/login', wrap(adminLogin));
router.post('/auth/logout', requireAuth, wrap(logout));
router.get('/auth/me', requireAuth, wrap(me));
router.post('/auth/change-password', requireAuth, wrap(changePassword));
router.get('/notifications', requireAuth, wrap(listNotifications));
router.patch('/notifications/:id/read', requireAuth, wrap(markNotificationRead));
router.get('/admin/dashboard', requireAuth, requireAdmin, wrap(adminDashboard));
router.get('/admin/audit-logs', requireAuth, requireAdmin, wrap(listAuditLogs));
router.get('/admin/reports', requireAuth, requireAdmin, wrap(report));
router.get('/profile', requireAuth, wrap(getProfile));
router.patch('/profile', requireAuth, wrap(updateProfile));
router.get('/profile/document-types', requireAuth, wrap(listDocumentTypes));
router.post('/profile/documents', requireAuth, upload.array('documents', 5), wrap(uploadDocuments));
router.get('/profile/documents/:documentId', requireAuth, wrap(downloadOwnDocument));
router.post('/profile/photo', requireAuth, upload.single('photo'), wrap(uploadProfilePhoto));
router.get('/admin/users', requireAuth, requireAdmin, wrap(listUsers));
router.patch('/admin/users/:id/status', requireAuth, requireAdmin, wrap(reviewUser));
router.post('/admin/users/:id/credentials', requireAuth, requireAdmin, wrap(setCredentials));
router.get('/admin/users/:id/documents', requireAuth, requireAdmin, wrap(listDocuments));
router.get('/admin/users/:id/documents/:documentId', requireAuth, requireAdmin, wrap(downloadDocument));
router.patch('/admin/users/:id/documents/:documentId/status', requireAuth, requireAdmin, wrap(reviewDocument));
router.get('/admin/document-types', requireAuth, requireAdmin, wrap(listAdminDocumentTypes));
router.post('/admin/document-types', requireAuth, requireAdmin, wrap(createDocumentType));
router.patch('/admin/document-types/:typeId', requireAuth, requireAdmin, wrap(updateDocumentType));
router.patch('/admin/users/:id/block', requireAuth, requireSuperAdmin, (req, res, next) => { req.body.status = 'BLOCKED'; next(); }, wrap(reviewUser));
router.get('/dashboard', requireAuth, wrap(dashboard));
router.get('/collaterals', requireAuth, wrap(listCollaterals));
router.post('/collaterals', requireAuth, wrap(createCollateral));
router.patch('/collaterals/:id/status', requireAuth, requireAdmin, wrap(updateCollateralStatus));
router.get('/loans', requireAuth, wrap(listLoans));
router.get('/loan-products', requireAuth, wrap(listProducts));
router.post('/loans', requireAuth, upload.array('evidence', 5), wrap(createLoan));
router.get('/loans/:id', requireAuth, wrap(getLoan));
router.patch('/loans/:id/status', requireAuth, requireAdmin, wrap(updateLoanStatus));
router.get('/repayments', requireAuth, wrap(listRepayments));
router.get('/loans/:loanId/repayments', requireAuth, wrap(getLoanRepaymentSummary));
router.post('/payments', requireAuth, wrap(createPayment));
router.get('/payments/:id/receipt', requireAuth, wrap(paymentReceipt));
router.get('/admin/payment-reports', requireAuth, requireAdmin, wrap(paymentReport));
router.patch('/admin/payments/:id/reconcile', requireAuth, requireAdmin, wrap(reconcilePayment));
export default router;